name: functional_status_codes_example
description: A simple one and modified http package example with use of functional_status_codes
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  functional_status_codes:
    path: ../
  http: any # From Google.

dev_dependencies:
  dart_code_metrics_presets: ^2.26.1 # DCM.
  lints: ^6.0.0 # From Google.
  test: ^1.26.3 # From Google.