name: functional_status_codes_example
description: A modified http package example with use of functional_status_codes
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  functional_status_codes:
    path: ../
  http: ^0.13.5 # From Google

dev_dependencies:
  dart_code_metrics: ^5.3.0 # Flutter Favorite
  lints: ^2.0.1 # From Google
  test: ^1.22.1 # From Google
