name: functional_status_codes_example
description: A simple one and modified http package example with use of functional_status_codes
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  functional_status_codes:
    path: ../
  http: any # ignore: avoid-any-version, it's exampe app.

dev_dependencies:
  dart_code_metrics_presets: ^2.29.0 # DCM.
  lints: ^6.1.0 # From Google.
  test: ^1.30.0 # From Google.