version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "Europe/Vienna"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"

  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "/example"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "Europe/Vienna"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"