version: 2.3.0
name: functional_status_codes
description: This package offers a functional approach to handling HTTP status codes.
maintainer: Roman Cinis
repository: https://github.com/tsinis/functional_status_codes
issue_tracker: https://github.com/tsinis/functional_status_codes/issues
topics:
 - status-codes
 - status-code
 - http
 - https
 - iana

environment:
  sdk: ^2.17.0

dev_dependencies:
  build_runner: any # From Google
  coverage: any # From Google
  dart_code_metrics: any # Flutter Favorite
  lints: any # From Google
  pana: any # From Google
  test: any # From Google

screenshots:
  - description: 'Good/Bad Comparison'
    path: doc/comparison.webp