name: functional_status_codes
description: This package offers a functional approach to handling HTTP status codes.
version: 1.0.1
maintainer: Roman Cinis
repository: https://github.com/tsinis/functional_status_codes
issue_tracker: https://github.com/tsinis/functional_status_codes/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.3 # From Google
  dart_code_metrics: ^5.3.0 # Flutter Favorite
  lints: ^2.0.1 # From Google
  test: ^1.22.1 # From Google
